pipeline {
    agent any

    stages {
        stage('Build image') {
            steps {
                script {
                    dockerImage = docker.build("$docker_repository:$tag_name","--no-cache ./nodejs/")
                }
            }
        }
        stage('Push image') {
            steps {
                script {
                    withDockerRegistry(
                        credentialsId: 'docker-user',
                        url: 'https://index.docker.io/v1/') {
                        dockerImage.push()
                    }
                }
            }
        }
        stage('Deployment') {
            steps {
                sh 'kubectl apply -f ./nodejs/node-app-deployment.yaml';
            }
        }
    }
}
